name: Build Watchman macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      ACTIONS_RUNTIME_TOKEN: ${{ github.token }}
      ACTIONS_CACHE_URL: ${ACTIONS_CACHE_URL:-"https://actions-cache.github.com/api/"}

    steps:
    - name: Clone Watchman
      uses: actions/checkout@v4
      with:
        repository: facebook/watchman
        path: watchman
        fetch-depth: 1
        submodules: recursive

    - name: Build Watchman
      working-directory: watchman
      run: |
        export CC=clang
        export CXX=clang++
        export GETDEPS_PACKAGE_DIR="$GITHUB_WORKSPACE/watchman/build/fbcode_builder/manifests"
        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          install-system-deps --recursive watchman
        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          build --src-dir="$PWD" --no-tests watchman

        # Debug: Show us the directory structure
        echo "Directory structure:"
        ls -R .
        echo "Finding watchman binaries..."
        find . -type f -name watchman

    - name: Create Package
      working-directory: watchman
      run: |
        mkdir -p package/watchman
        # Look for binaries in build directory and _build directory
        for path in $(find . -type f -name watchman -o -name watchmanctl 2>/dev/null); do
          if [[ -x "$path" ]]; then
            echo "Found binary: $path"
            cp "$path" package/watchman/
          fi
        done
        cp LICENSE package/watchman/
        cd package
        tar -czf watchman-macos.tar.gz watchman/

        # Debug: Show what we packaged
        echo "Package contents:"
        tar tvf watchman-macos.tar.gz

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: watchman-macos
        path: watchman/package/watchman-macos.tar.gz
        retention-days: 7
