name: Build Watchman macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        brew install fmt boost googletest glog
        python -m pip install --upgrade pip
        pip install cython

    - name: Debug Watchman Dependencies
      run: |
        git clone --depth 1 --single-branch --branch main --no-tags \
          https://github.com/facebook/watchman.git
        cd watchman
        echo "Examining CMakeLists.txt for edencommon configuration:"
        grep -A 5 -B 5 edencommon CMakeLists.txt
        echo "\nChecking for any edencommon files:"
        find . -type f -exec grep -l "edencommon" {} \;
        echo "\nChecking CMake files:"
        find . -name "*.cmake" -o -name "CMakeLists.txt" | xargs cat

    - name: Build
      if: false  # Temporarily disable build step
      run: |
        cd watchman
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DWATCHMAN_BUILD_TESTS=ON \
          -DOPENSSL_ROOT_DIR=$(brew --prefix openssl@3) \
          -DGTEST_ROOT=$(brew --prefix googletest)
        cmake --build build --config Release -j$(sysctl -n hw.ncpu)

    - name: Create Package
      if: false  # Temporarily disable package step
      run: |
        cd watchman
        mkdir -p package/watchman
        cp build/watchman package/watchman/
        cp build/watchmanctl package/watchman/
        cp LICENSE package/watchman/
        cd package
        tar -czf watchman-macos.tar.gz watchman/

    - name: Upload Artifact
      if: false  # Temporarily disable upload step
      uses: actions/upload-artifact@v4
      with:
        name: watchman-macos
        path: watchman/package/watchman-macos.tar.gz
        retention-days: 7
