name: Build Watchman macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      DEPENDENCY_DIR: /usr/local/var/getdeps
      GETDEPS_BUILD_DIR: /usr/local/var/getdeps/build
      CCACHE_DIR: /Users/runner/work/_temp/ccache
      CCACHE_MAXSIZE: 1G
      ACTIONS_RUNTIME_TOKEN: ${{ github.token }}
      ACTIONS_CACHE_URL: ${ACTIONS_CACHE_URL:-"https://actions-cache.github.com/api/"}

    steps:
    - name: Clone Watchman
      uses: actions/checkout@v4
      with:
        repository: facebook/watchman
        path: watchman
        fetch-depth: 1
        submodules: recursive

    - name: Install ccache
      run: |
        brew install ccache
        ccache --version
        ccache --max-size=$CCACHE_MAXSIZE
        ccache --set-config=hash_dir=false

    - name: ccache cache
      uses: actions/cache@v3
      with:
        path: ${{ env.CCACHE_DIR }}
        key: macos-ccache-v1-${{ github.sha }}
        restore-keys: macos-ccache-v1-

    - name: getdeps cache
      uses: actions/cache@v3
      with:
        path: /usr/local/var/getdeps
        key: macos-getdeps-v1-${{ github.sha }}
        restore-keys: macos-getdeps-v1-

    - name: Build Watchman
      working-directory: watchman
      run: |
        export CC="ccache clang"
        export CXX="ccache clang++"
        export GETDEPS_PACKAGE_DIR="$GITHUB_WORKSPACE/watchman/build/fbcode_builder/manifests"
        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          install-system-deps --recursive watchman
        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          build --src-dir="$PWD" --no-tests watchman

    - name: Create Package
      run: |
        cd watchman
        mkdir -p package/watchman
        find ${GETDEPS_BUILD_DIR} -type f -name watchman -exec cp {} package/watchman/ \;
        find ${GETDEPS_BUILD_DIR} -type f -name watchmanctl -exec cp {} package/watchman/ \;
        cp LICENSE package/watchman/
        cd package
        tar -czf watchman-macos.tar.gz watchman/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: watchman-macos
        path: watchman/package/watchman-macos.tar.gz
        retention-days: 7
