name: Build Watchman macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      DEPENDENCY_DIR: /usr/local/var/getdeps
      GETDEPS_BUILD_DIR: /usr/local/var/getdeps/build
      ACTIONS_RUNTIME_TOKEN: ${{ github.token }}
      # Fix: Remove variable interpolation in environment variable definition
      ACTIONS_CACHE_URL: ${{ vars.ACTIONS_CACHE_URL || 'https://actions-cache.github.com/api/' }}

    steps:
    - name: Clone Watchman
      uses: actions/checkout@v4
      with:
        repository: facebook/watchman
        path: watchman
        fetch-depth: 1
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: getdeps cache
      uses: actions/cache@v3
      with:
        path: /usr/local/var/getdeps
        key: macos-getdeps-v1-${{ github.sha }}
        restore-keys: |
          macos-getdeps-v1-

    - name: Build Watchman
      working-directory: watchman
      run: |
        # Fix: Use explicit Python path and add error handling
        export CC=clang
        export CXX=clang++
        export GETDEPS_PACKAGE_DIR="${GITHUB_WORKSPACE}/watchman/build/fbcode_builder/manifests"

        # Add error checking
        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          install-system-deps --recursive watchman || exit 1

        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          build --src-dir="${PWD}" --no-tests watchman || exit 1

    - name: Create Package
      run: |
        cd watchman || exit 1
        mkdir -p package/watchman

        # Add error checking for required files
        if ! find "${GETDEPS_BUILD_DIR}" -type f -name watchman -exec cp {} package/watchman/ \;; then
          echo "Error: watchman binary not found"
          exit 1
        fi

        if ! find "${GETDEPS_BUILD_DIR}" -type f -name watchmanctl -exec cp {} package/watchman/ \;; then
          echo "Error: watchmanctl binary not found"
          exit 1
        fi

        if [ ! -f LICENSE ]; then
          echo "Error: LICENSE file not found"
          exit 1
        fi

        cp LICENSE package/watchman/
        cd package || exit 1
        tar -czf watchman-macos.tar.gz watchman/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: watchman-macos
        path: watchman/package/watchman-macos.tar.gz
        retention-days: 7
