name: Build Watchman macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      ACTIONS_RUNTIME_TOKEN: ${{ github.token }}
      ACTIONS_CACHE_URL: ${ACTIONS_CACHE_URL:-"https://actions-cache.github.com/api/"}
      TMPDIR: /tmp/watchman-build

    steps:
    - name: Clone Watchman
      uses: actions/checkout@v4
      with:
        repository: facebook/watchman
        path: watchman
        fetch-depth: 1
        submodules: recursive

    - name: Build Watchman
      working-directory: watchman
      run: |
        # Create and use our own temp directory to make it easier to find builds
        mkdir -p $TMPDIR
        export CC=clang
        export CXX=clang++
        export GETDEPS_PACKAGE_DIR="$GITHUB_WORKSPACE/watchman/build/fbcode_builder/manifests"

        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          install-system-deps --recursive watchman
        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          build --src-dir="$PWD" --no-tests watchman

        echo "Build complete, contents of TMPDIR:"
        ls -R "$TMPDIR"

    - name: Create Package
      run: |
        cd watchman
        mkdir -p package/watchman

        # Look in our controlled temp directory
        for binary in watchman watchmanctl; do
          echo "Looking for $binary in $TMPDIR"
          if found=$(find "$TMPDIR" -type f -name "$binary" 2>/dev/null); then
            echo "Found $binary at: $found"
            while IFS= read -r path; do
              if [ -x "$path" ]; then
                echo "Copying executable $binary from: $path"
                cp "$path" package/watchman/
              fi
            done <<< "$found"
          fi
        done

        cp LICENSE package/watchman/

        echo "Final package contents:"
        ls -l package/watchman/

        cd package
        tar -czf watchman-macos.tar.gz watchman/
        echo "Archive contents:"
        tar tvf watchman-macos.tar.gz

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: watchman-macos
        path: watchman/package/watchman-macos.tar.gz
        retention-days: 7
