name: Build Watchman macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        brew install fmt boost googletest glog
        python -m pip install --upgrade pip
        pip install cython

    - name: Clone and Debug Dependencies
      run: |
        git clone --depth 1 --single-branch --branch main --no-tags \
          https://github.com/facebook/watchman.git
        cd watchman
        git submodule update --init --recursive --depth 1
        echo "Submodules:"
        git submodule status
        echo "\nContent of watchman directory:"
        ls -la
        echo "\nSearching for edencommon:"
        find . -type d -name "edencommon" -o -name "eden-common"
        echo "\nSearching for relevant CMakeLists.txt:"
        find . -name "CMakeLists.txt" -exec grep -l "edencommon" {} \;

    - name: Build
      run: |
        cd watchman
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DWATCHMAN_BUILD_TESTS=ON \
          -DOPENSSL_ROOT_DIR=$(brew --prefix openssl@3) \
          -DGTEST_ROOT=$(brew --prefix googletest)
        cmake --build build --config Release -j$(sysctl -n hw.ncpu)

    - name: Create Package
      run: |
        cd watchman
        mkdir -p package/watchman
        cp build/watchman package/watchman/
        cp build/watchmanctl package/watchman/
        cp LICENSE package/watchman/
        cd package
        tar -czf watchman-macos.tar.gz watchman/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: watchman-macos
        path: watchman/package/watchman-macos.tar.gz
        retention-days: 7
