name: Build Watchman macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      DEPENDENCY_DIR: /usr/local/var/getdeps
      GETDEPS_BUILD_DIR: /usr/local/var/getdeps/build
      ACTIONS_RUNTIME_TOKEN: ${{ github.token }}
      ACTIONS_CACHE_URL: ${{ vars.ACTIONS_CACHE_URL || 'https://actions-cache.github.com/api/' }}
      CFLAGS: "-w"
      CXXFLAGS: "-w"

    steps:
    - name: Clone Watchman
      uses: actions/checkout@v4
      with:
        repository: facebook/watchman
        path: watchman
        fetch-depth: 1
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: getdeps cache
      uses: actions/cache@v3
      with:
        path: /usr/local/var/getdeps
        key: macos-getdeps-v1-${{ github.sha }}
        restore-keys: |
          macos-getdeps-v1-

    - name: Build Watchman
      working-directory: watchman
      run: |
        export CC=clang
        export CXX=clang++
        export GETDEPS_PACKAGE_DIR="${GITHUB_WORKSPACE}/watchman/build/fbcode_builder/manifests"

        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          install-system-deps --recursive watchman 2>/dev/null || exit 1

        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          build --src-dir="${PWD}" --no-tests watchman 2>/dev/null || exit 1

    - name: Create Package
      run: |
        cd watchman || exit 1
        mkdir -p package/watchman

        echo "Finding watchman binaries..."
        echo "Looking for files in build directory:"
        find . -type f -name "watchman" -o -name "watchmanctl"

        echo -e "\nGetting build info from getdeps..."
        BUILD_DIR=$(python3 build/fbcode_builder/getdeps.py --allow-system-packages show-build-dir watchman)
        INST_DIR=$(python3 build/fbcode_builder/getdeps.py --allow-system-packages show-inst-dir watchman)

        echo "Build directory: ${BUILD_DIR}"
        echo "Install directory: ${INST_DIR}"

        # Search in common build locations
        POSSIBLE_DIRS=(
          "./build/watchman"
          "./build/_build"
          "./build/_install"
          "${BUILD_DIR}"
          "${INST_DIR}"
        )

        # Show contents of possible build directories
        for DIR in "${POSSIBLE_DIRS[@]}"; do
          if [ -d "$DIR" ]; then
            echo -e "\nContents of $DIR:"
            ls -R "$DIR"
          fi
        done

        # First try the install directory
        if [ -n "${INST_DIR}" ] && [ -d "${INST_DIR}/bin" ]; then
          echo "Trying install directory..."
          cp "${INST_DIR}/bin/watchman" package/watchman/ && \
          cp "${INST_DIR}/bin/watchmanctl" package/watchman/
        # Then try the build directory
        elif [ -n "${BUILD_DIR}" ] && [ -d "${BUILD_DIR}" ]; then
          echo "Trying build directory..."
          find "${BUILD_DIR}" -type f -name watchman -exec cp {} package/watchman/ \;
          find "${BUILD_DIR}" -type f -name watchmanctl -exec cp {} package/watchman/ \;
        # Finally try local build directory
        elif [ -d "build" ]; then
          echo "Trying local build directory..."
          find build -type f -name watchman -exec cp {} package/watchman/ \;
          find build -type f -name watchmanctl -exec cp {} package/watchman/ \;
        else
          echo "Error: Could not find watchman binaries in any expected location"
          exit 1
        fi

        if [ ! -f LICENSE ]; then
          echo "Error: LICENSE file not found"
          exit 1
        fi

        # Verify we found the binaries
        if [ ! -f "package/watchman/watchman" ] || [ ! -f "package/watchman/watchmanctl" ]; then
          echo "Error: Failed to copy one or both binaries"
          exit 1
        fi

        cp LICENSE package/watchman/
        cd package || exit 1
        tar -czf watchman-macos.tar.gz watchman/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: watchman-macos
        path: watchman/package/watchman-macos.tar.gz
        retention-days: 7
