name: Build Watchman macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      ACTIONS_RUNTIME_TOKEN: ${{ github.token }}
      ACTIONS_CACHE_URL: ${ACTIONS_CACHE_URL:-"https://actions-cache.github.com/api/"}

    steps:
    - name: Clone Watchman
      uses: actions/checkout@v4
      with:
        repository: facebook/watchman
        path: watchman
        fetch-depth: 1
        submodules: recursive

    - name: Build Watchman
      working-directory: watchman
      run: |
        export CC=clang
        export CXX=clang++
        export GETDEPS_PACKAGE_DIR="$GITHUB_WORKSPACE/watchman/build/fbcode_builder/manifests"
        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          install-system-deps --recursive watchman
        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          build --src-dir="$PWD" --no-tests watchman

    - name: Create Package
      run: |
        cd watchman
        mkdir -p package/watchman

        # Get the fbcode builder directory
        FBCODE_DIR=$(find /private/var/folders -type d -name "fbcode_builder_getdeps-*" -print -quit)
        echo "Found fbcode directory: $FBCODE_DIR"

        # Copy from installed location
        INSTALLED_DIR="$FBCODE_DIR/installed/watchman/bin"
        if [ -d "$INSTALLED_DIR" ]; then
          echo "Copying from installed directory: $INSTALLED_DIR"
          cp "$INSTALLED_DIR/watchman" package/watchman/
          cp "$INSTALLED_DIR/watchmanctl" package/watchman/
        else
          echo "Installed directory not found, trying build directory"
          BUILD_BIN="$FBCODE_DIR/build/watchman/bin/watchman"
          BUILD_CTL="$FBCODE_DIR/build/watchman/watchman/cli/release/watchmanctl"

          [ -f "$BUILD_BIN" ] && cp "$BUILD_BIN" package/watchman/
          [ -f "$BUILD_CTL" ] && cp "$BUILD_CTL" package/watchman/
        fi

        cp LICENSE package/watchman/

        echo "Final package contents:"
        ls -l package/watchman/

        cd package
        tar -czf watchman-macos.tar.gz watchman/
        echo "Archive contents:"
        tar tvf watchman-macos.tar.gz

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: watchman-macos
        path: watchman/package/watchman-macos.tar.gz
        retention-days: 7
