name: Build Watchman macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      ACTIONS_RUNTIME_TOKEN: ${{ github.token }}
      ACTIONS_CACHE_URL: ${ACTIONS_CACHE_URL:-"https://actions-cache.github.com/api/"}

    steps:
    - name: Clone Watchman
      uses: actions/checkout@v4
      with:
        repository: facebook/watchman
        path: watchman
        fetch-depth: 1
        submodules: recursive

    - name: Build Watchman
      working-directory: watchman
      run: |
        export CC=clang
        export CXX=clang++
        export GETDEPS_PACKAGE_DIR="$GITHUB_WORKSPACE/watchman/build/fbcode_builder/manifests"
        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          install-system-deps --recursive watchman
        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          build --src-dir="$PWD" --no-tests watchman

        # Debug: Show where builds might be
        echo "Looking for build directories and binaries:"
        echo "In /tmp:"
        find /tmp -type d -name "*watchman*" -o -name "*fbcode*" 2>/dev/null || true
        echo "In /private/var/folders:"
        find /private/var/folders -type d -name "*watchman*" -o -name "*fbcode*" 2>/dev/null || true
        echo "In current directory:"
        find . -type d -name "*watchman*" -o -name "*fbcode*" 2>/dev/null || true

        echo "Looking for binaries:"
        echo "In /tmp:"
        find /tmp -type f -name "watchman" -o -name "watchmanctl" 2>/dev/null || true
        echo "In /private/var/folders:"
        find /private/var/folders -type f -name "watchman" -o -name "watchmanctl" 2>/dev/null || true
        echo "In current directory:"
        find . -type f -name "watchman" -o -name "watchmanctl" 2>/dev/null || true

    - name: Create Package
      run: |
        cd watchman
        mkdir -p package/watchman

        # Look everywhere for the binaries
        for location in "/tmp" "/private/var/folders" "$PWD"; do
          echo "Searching in $location"
          for binary in watchman watchmanctl; do
            if BINARY_PATH=$(find "$location" -type f -name "$binary" 2>/dev/null); then
              echo "Found $binary at: $BINARY_PATH"
              cp "$BINARY_PATH" package/watchman/
            fi
          done
        done

        # Package up what we found
        cp LICENSE package/watchman/
        cd package
        tar -czf watchman-macos.tar.gz watchman/

        # Show what we got
        echo "Archive contents:"
        tar tvf watchman-macos.tar.gz

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: watchman-macos
        path: watchman/package/watchman-macos.tar.gz
        retention-days: 7
