name: Build Watchman macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      ACTIONS_RUNTIME_TOKEN: ${{ github.token }}
      ACTIONS_CACHE_URL: ${ACTIONS_CACHE_URL:-"https://actions-cache.github.com/api/"}

    steps:
    - name: Clone Watchman
      uses: actions/checkout@v4
      with:
        repository: facebook/watchman
        path: watchman
        fetch-depth: 1
        submodules: recursive

    - name: Build Watchman
      working-directory: watchman
      run: |
        export CC=clang
        export CXX=clang++
        export GETDEPS_PACKAGE_DIR="$GITHUB_WORKSPACE/watchman/build/fbcode_builder/manifests"
        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          install-system-deps --recursive watchman
        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          build --src-dir="$PWD" --no-tests watchman

        # Debug: Show the temp build directory
        echo "Temp build directory contents:"
        FBCODE_DIR=$(find /private/var/folders -type d -name "fbcode_builder_getdeps-*" 2>/dev/null)
        ls -R "$FBCODE_DIR" || true

    - name: Create Package
      run: |
        cd watchman
        mkdir -p package/watchman

        # Look in the temp build directory
        FBCODE_DIR=$(find /private/var/folders -type d -name "fbcode_builder_getdeps-*" 2>/dev/null)
        if [ -n "$FBCODE_DIR" ]; then
          echo "Found fbcode build directory: $FBCODE_DIR"
          for binary in watchman watchmanctl; do
            if BINARY_PATH=$(find "$FBCODE_DIR" -type f -name "$binary" 2>/dev/null); then
              echo "Found $binary at $BINARY_PATH"
              cp "$BINARY_PATH" package/watchman/
            fi
          done
        else
          echo "Could not find fbcode build directory!"
          exit 1
        fi

        cp LICENSE package/watchman/
        cd package
        tar -czf watchman-macos.tar.gz watchman/

        # Verify contents
        echo "Archive contents:"
        tar tvf watchman-macos.tar.gz

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: watchman-macos
        path: watchman/package/watchman-macos.tar.gz
        retention-days: 7
