name: Build Watchman macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      DEPENDENCY_DIR: /usr/local/var/getdeps
      GETDEPS_BUILD_DIR: /usr/local/var/getdeps/build
      ACTIONS_RUNTIME_TOKEN: ${{ github.token }}
      ACTIONS_CACHE_URL: ${{ vars.ACTIONS_CACHE_URL || 'https://actions-cache.github.com/api/' }}
      CFLAGS: "-w"
      CXXFLAGS: "-w"

    steps:
    - name: Clone Watchman
      uses: actions/checkout@v4
      with:
        repository: facebook/watchman
        path: watchman
        fetch-depth: 1
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: getdeps cache
      uses: actions/cache@v3
      with:
        path: /usr/local/var/getdeps
        key: macos-getdeps-v1-${{ github.sha }}
        restore-keys: |
          macos-getdeps-v1-

    - name: Build Watchman
      working-directory: watchman
      run: |
        export CC=clang
        export CXX=clang++
        export GETDEPS_PACKAGE_DIR="${GITHUB_WORKSPACE}/watchman/build/fbcode_builder/manifests"

        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          install-system-deps --recursive watchman 2>/dev/null || exit 1

        python3 build/fbcode_builder/getdeps.py --allow-system-packages \
          build --src-dir="${PWD}" --no-tests watchman 2>/dev/null || exit 1

    - name: Create Package
      run: |
        cd watchman || exit 1
        mkdir -p package/watchman

        # Get the install directory from getdeps
        INST_DIR=$(python3 build/fbcode_builder/getdeps.py --allow-system-packages show-inst-dir watchman)
        echo "Install directory: ${INST_DIR}"

        if [ ! -f "${INST_DIR}/bin/watchman" ] || [ ! -f "${INST_DIR}/bin/watchmanctl" ]; then
          echo "Error: Binaries not found in ${INST_DIR}/bin"
          exit 1
        fi

        echo "Copying binaries from ${INST_DIR}/bin"
        cp "${INST_DIR}/bin/watchman" "${INST_DIR}/bin/watchmanctl" package/watchman/ || {
          echo "Error: Failed to copy binaries"
          exit 1
        }

        if [ ! -f LICENSE ]; then
          echo "Error: LICENSE file not found"
          exit 1
        fi

        cp LICENSE package/watchman/
        cd package || exit 1
        tar -czf watchman-macos.tar.gz watchman/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: watchman-macos
        path: watchman/package/watchman-macos.tar.gz
        retention-days: 7
